// <auto-generated />
using System;
using Happy_Analysis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Happy_Analysis.Migrations
{
    [DbContext(typeof(AnalysisContext))]
    partial class AnalysisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Happy_Analysis.Models.DataModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage1")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Percentage2")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Percentage3")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Percentage4")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Percentage5")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Percentage6")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("ID");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Happy_Analysis.Models.DataPoint", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("X1")
                        .HasColumnType("int");

                    b.Property<int>("X2")
                        .HasColumnType("int");

                    b.Property<int>("X3")
                        .HasColumnType("int");

                    b.Property<int>("X4")
                        .HasColumnType("int");

                    b.Property<int>("X5")
                        .HasColumnType("int");

                    b.Property<int>("X6")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("DataPoints");
                });

            modelBuilder.Entity("Happy_Analysis.Models.ModelRun", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("F1_Score")
                        .HasColumnType("decimal(6,5)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReferencePoint")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("Run_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
